### ISSUE TITLE
A4.3.1 - A screenshot of the SLA generated in iTop, and its association to the maintenance service as created in the iTop tool.

### ISSUE THREAD

**Issue by ananovmon** [gii-is-psg2/PSG2-1819-G5-50#34]

**Comment by Capi9888** [comment]
### **Captura de propiedades**
![Sla1](https://user-images.githubusercontent.com/47814345/57918730-a54a1000-7897-11e9-8cf5-d0ea5247f0d4.png)
### **Captura de SLTs**
![Sla2](https://user-images.githubusercontent.com/47814345/57918764-b4c95900-7897-11e9-9003-912698c27bcd.png)
### **Captura de acuerdos con clientes**
![Sla3](https://user-images.githubusercontent.com/47814345/57918776-bb57d080-7897-11e9-8326-93f1b67c4dd0.png)
