### ISSUE TITLE
A4.2.3 - Structure of the CMDB, including some examples of the identified Configurable Items

### ISSUE THREAD

**Issue by antonihipona** [gii-is-psg2/PSG2-1819-G5-50#35]

**Comment by ananovmon** [comment]
![EC-PC](https://user-images.githubusercontent.com/47814299/57928205-63799380-78b0-11e9-9c55-b2f688707601.PNG)
![EC-SW](https://user-images.githubusercontent.com/47814299/57928210-67a5b100-78b0-11e9-88ee-2de2d251b815.PNG)
![BBDD](https://user-images.githubusercontent.com/47814299/57928212-6aa0a180-78b0-11e9-97c7-7515a812cbbd.PNG)
![EC-GPU](https://user-images.githubusercontent.com/47814299/57928218-6d9b9200-78b0-11e9-8d16-1e7844baf369.PNG)
![EC- TOTAL](https://user-images.githubusercontent.com/47814299/57928221-6ffdec00-78b0-11e9-9448-6ead88a2ec2a.PNG)
