### ISSUE TITLE
A4.2.6 - Report with the solutions provided to the service requests.

### ISSUE THREAD

**Issue by antonihipona** [gii-is-psg2/PSG2-1819-G5-50#40]

**Comment by angel96** [comment]
# Problema 1
![Problema 1](https://user-images.githubusercontent.com/16750517/57925512-c36c3c00-78a8-11e9-8891-82698669e15c.PNG)

# Problema 2
![Problema 2A](https://user-images.githubusercontent.com/16750517/57925946-30340600-78aa-11e9-8d97-449a084671f3.PNG)

![Problema 2B](https://user-images.githubusercontent.com/16750517/57925948-31653300-78aa-11e9-8172-3bedfa8617ff.PNG)
# Problema 3

![Problema 3](https://user-images.githubusercontent.com/16750517/57925958-375b1400-78aa-11e9-856b-214aff996d1c.PNG)


# Problema 5

![Problema 5](https://user-images.githubusercontent.com/16750517/57925964-3c1fc800-78aa-11e9-86f7-8953e0f016e2.PNG)

# Problema 6

![Problema 6](https://user-images.githubusercontent.com/16750517/57925973-43df6c80-78aa-11e9-85b5-a998b9ac3e96.PNG)
